version: 2
updates:
  # Enable version updates for npm (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "andimclean"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm (xcfreader package)
  - package-ecosystem: "npm"
    directory: "/packages/xcfreader"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "andimclean"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm (ui-xcfimage package)
  - package-ecosystem: "npm"
    directory: "/packages/ui-xcfimage"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "andimclean"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "andimclean"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
